src/apps/answer/urls.py
from django.urls import path

from .views import AnswerListView

app_name = 'answer'

urlpatterns = [
    path('list/',
         AnswerListView.as_view(), name='list'),
]

src/apps/resume/urls.py
from django.urls import path

from .views import ResumeDetailView

app_name = 'resume'

urlpatterns = [
    path('detail/<int:pk>/',
         ResumeDetailView.as_view(), name='detail'),
]

src/apps/users/urls.py
from django.urls import path
from django.conf.urls import include

from src.apps.users.views import RegistrationView, ProfileView, LoginView


urlpatterns = [
    path('register/worker/', RegistrationView.as_view(),
         name='registration-user'),
    path('register/hr/', RegistrationView.as_view(),
         name='registration-hr'),
    path('register/profile/', ProfileView.as_view(),
         name='registration-profile'),
    path('login/', LoginView.as_view(),
         name='login'),
    # path('profile/update/<int:pk>/', ProfileView.as_view(), name='profile-update'),
    path('', include('django.contrib.auth.urls')),

]

src/apps/vacancy/urls.py
from django.urls import path

from .views import VacancyDetailView, VacancyCreateView, VacancyListView, \
    VacancyUpdateView, VacancyDeleteView

app_name = 'vacancy'

urlpatterns = [
    path('detail/<int:pk>/',
         VacancyDetailView.as_view(), name='detail'),
    path('create/',
         VacancyCreateView.as_view(), name='create'),
    path('list/',
         VacancyListView.as_view(), name='list'),
    path('update/<int:pk>/',
         VacancyUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/',
         VacancyDeleteView.as_view(), name='delete'),
]

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import TemplateView

from src.apps.users.views import RegistrationView, ProfileView, \
    ProfileUpdateView
from src.apps.vacancy.views import tag_create_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('role_choice/', TemplateView.as_view(
        template_name='registration/role_choice.html'), name='sign_up'),
    path('features/', TemplateView.as_view(
        template_name='components/features.html'), name='features'),
    path('contacts/', TemplateView.as_view(
        template_name='components/contacts.html'), name='contacts'),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('dashboard/worker/',
         include('src.apps.account_worker.urls'),
         name='dashboard_worker'),
    path('dashboard/hr/', include('src.apps.account_hr.urls',
         namespace='dashboard_hr')),
    path('accounts/', include('src.apps.users.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('vacancies/',
         include('src.apps.vacancy.urls', namespace='vacancies')),
    path('answers/',
         include('src.apps.answer.urls', namespace='answers')),
    path('resumes/',
         include('src.apps.resume.urls', namespace='resumes')),
    path('add/tags/', tag_create_view, name='tag_create'),
    path('terms/', TemplateView.as_view(
        template_name='components/terms_of_use.html'), name='terms'),
    path('privacy/', TemplateView.as_view(
        template_name='components/privacy_policy.html'), name='privacy'),
    path('questions/',
         include('src.apps.question.urls', namespace='questions')),
    path('profile_update/<int:pk>/', ProfileUpdateView.as_view(), name='profile_update')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/answer/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from src.apps.account_worker.models import AccountWorker
from src.apps.question.models import Question


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    account_worker = models.ManyToManyField(
        AccountWorker, related_name='answers', verbose_name=_('Worker'))
    text = models.TextField(_('Text'))

src/apps/account_hr/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from src.apps.question.models import Answer, Question
from src.apps.resume.models import Resume
from src.apps.vacancy.models import Vacancy
from .models import AccountHr


class DashboardView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/index.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['vacancies'] = Vacancy.objects.filter(
            account_hr__user_id=self.request.user.id
        )[:5]
        context['answers'] = Answer.objects.filter(
            question__account_hr__user_id=self.request.user.id
        )[:5]
        return context


class DashboardVacancyListView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/vacancy/list.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardVacancyListView, self).get_context_data(**kwargs)
        context['vacancies'] = Vacancy.objects.filter(
            account_hr__user_id=self.request.user.id
        )
        return context


class DashboardAnswerListView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/answer/list.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardAnswerListView, self).get_context_data(**kwargs)
        context['object_list'] = Answer.objects.filter(
            question__account_hr__user_id=self.request.user.id
        )
        return context


class DashboardResumeListView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/resume/list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardResumeListView, self).get_context_data(**kwargs)
        context['object_list'] = Resume.objects.all()
        return context


class DashboardResumeDetailView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/resume/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardResumeDetailView, self).get_context_data(**kwargs)
        context['object'] = Resume.objects.get(id=kwargs['pk'])
        return context


class DashboardVacancyDetailView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/vacancy/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardVacancyDetailView, self).get_context_data(**kwargs)
        vacancy = Vacancy.objects.get(id=kwargs['pk'])
        context['object'] = vacancy
        context['questions'] = Question.objects.filter(vacancy=vacancy)
        return context

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        return reverse_lazy('dashboard_hr:main')

src/apps/account_worker/views/education.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from src.apps.resume.models import Education
from ..forms import EducationForm
from .mixins import (
    EduSkillJobSuccessUrlMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobAjaxMixin, worker_access)


@method_decorator((login_required, worker_access), name='dispatch')
class EducationUpdateView(ResumeEduSkillJobContextMixin,
                          EduSkillJobSuccessUrlMixin, UpdateView):
    form_class = EducationForm
    model = Education
    template_name = 'dashboard_worker/education/update.html'


@method_decorator((login_required, worker_access), name='dispatch')
class EducationCreateView(
    EduSkillJobSuccessUrlMixin, EduSkillJobAjaxMixin,
    ResumeEduSkillJobContextMixin, CreateView
):
    form_class = EducationForm
    model = Education
    template_name = 'dashboard_worker/education/create.html'


@method_decorator((login_required, worker_access), name='dispatch')
class EducationDeleteView(ResumeEduSkillJobContextMixin,
                          EduSkillJobSuccessUrlMixin, DeleteView):
    model = Education
    template_name = 'dashboard_worker/education/delete.html'

src/apps/account_worker/views/job.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from src.apps.resume.models import Job
from ..forms import JobForm
from .mixins import (
    EduSkillJobSuccessUrlMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobAjaxMixin, worker_access)


@method_decorator((login_required, worker_access), name='dispatch')
class JobCreateView(
    EduSkillJobAjaxMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobSuccessUrlMixin, CreateView
):
    form_class = JobForm
    model = Job
    template_name = 'dashboard_worker/job/create.html'


@method_decorator((login_required, worker_access), name='dispatch')
class JobUpdateView(ResumeEduSkillJobContextMixin,
                    EduSkillJobSuccessUrlMixin, UpdateView):
    form_class = JobForm
    model = Job
    template_name = 'dashboard_worker/job/update.html'


@method_decorator((login_required, worker_access), name='dispatch')
class JobDeleteView(ResumeEduSkillJobContextMixin,
                    EduSkillJobSuccessUrlMixin, DeleteView):
    model = Job
    template_name = 'dashboard_worker/job/delete.html'

src/apps/account_worker/views/mixins.py
from django.urls import reverse_lazy
from django.views.generic.base import ContextMixin
from django.shortcuts import get_object_or_404
from django.http import JsonResponse, Http404
from django.contrib.auth import get_user_model

from src.apps.resume.models import Resume
from src.apps.question.models import Question
from ..models import WorkerAnswered


User = get_user_model()


class EduSkillJobSuccessUrlMixin:
    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'dashboard_worker:dashboard_worker_resume_update',
            kwargs={
                'pk': self.kwargs.get('resume_pk'),
                'worker_pk': self.kwargs.get('worker_pk')
            }
        )


class ResumeEduSkillJobContextMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        context = super(
            ResumeEduSkillJobContextMixin, self).get_context_data(**kwargs)
        if self.kwargs.get('resume_pk'):
            context['resume_pk'] = self.kwargs.get('resume_pk')
            resume = get_object_or_404(Resume, pk=self.kwargs.get('resume_pk'))
        else:
            context['resume_pk'] = self.kwargs.get('pk')
            resume = get_object_or_404(Resume, pk=self.kwargs.get('pk'))
        context['title'] = resume.title
        context['worker_pk'] = self.kwargs.get('worker_pk')
        return context


class EduSkillJobAjaxMixin:
    def form_invalid(self, form):
        if self.request.is_ajax():
            if self.request.POST['tag'] == 'create':
                form = self.form_class()
                response_dict = {'response': str(form)}
                return JsonResponse(response_dict)
            raise Http404
        else:
            return super(EduSkillJobAjaxMixin, self).form_invalid(form)

    def form_valid(self, form):
        if self.request.is_ajax():
            if self.request.POST['tag'] == 'add':
                form = self.form_class(self.request.POST)
                if form.is_valid():
                    if self.form_class.__name__ == 'AnswerForm':
                        form.save(commit=False)
                        form.instance.question = get_object_or_404(Question, pk=self.request.POST['question'])
                        form.save()
                        user = get_object_or_404(User, pk=self.request.user.pk)
                        worker = user.workers.is_created(user=user)
                        if user.workers.is_created(user=user).answer.filter(
                                question=form.instance.question.pk).first():
                            answer = user.workers.is_created(user=user).answer.get(
                                question=form.instance.question.pk)
                            user.workers.is_created(user=user).answer.remove(answer)
                            answer.delete()
                        user.workers.is_created(user=user).answer.add(form.instance)
                        form.save()
                        answered = WorkerAnswered.objects.create(
                            worker=worker, question=form.instance.question,
                            answer=form.instance)
                        answered.save()
                        response_dict = {'response': form.instance.answer}
                    form.save()
                    if self.form_class.__name__ == 'EducationForm':
                        response_dict = {
                            'id': form.instance.pk,
                            'name_institution': form.instance.name_institution
                        }
                    elif self.form_class.__name__ == 'SkillForm':
                        response_dict = {
                            'id': form.instance.pk,
                            'name': form.instance.name
                        }
                    elif self.form_class.__name__ == 'JobForm':
                        response_dict = {
                            'id': form.instance.pk,
                            'name_company': form.instance.name_company
                        }
                    return JsonResponse(response_dict)
            else:
                raise Http404
        obj = form.save(commit=False)
        resume = get_object_or_404(Resume, pk=self.kwargs.get('resume_pk'))
        obj.save()
        if self.form_class.__name__ == 'EducationForm':
            resume.education.add(obj)
        elif self.form_class.__name__ == 'SkillForm':
            resume.skill.add(obj)
        elif self.form_class.__name__ == 'JobForm':
            resume.job.add(obj)
        resume.save()
        return super(EduSkillJobAjaxMixin, self).form_valid(form)


def worker_access(function):
    def wrapper(request, *args, **kwargs):
        if request.is_ajax():
            return function(request, *args, **kwargs)

        user = get_object_or_404(User, username=request.user)
        worker = user.workers.is_created(user=user)
        pk = kwargs.get('worker_pk') or kwargs.get('pk')
        if worker.pk != int(pk):
            raise Http404

        return function(request, *args, **kwargs)

    return wrapper


class QuestionContextMixin(ContextMixin):
    def get_context_data(self, *args, **kwargs):
        context = super(
            QuestionContextMixin, self).get_context_data(**kwargs)
        context['worker_pk'] = self.kwargs.get('worker_pk')
        return context

src/apps/account_worker/views/question.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

from src.apps.question.models import Question, Answer
from ..forms import AnswerForm
from .mixins import (
    worker_access, QuestionContextMixin, EduSkillJobAjaxMixin)


@method_decorator((login_required, worker_access), name='dispatch')
class QuestionsListView(QuestionContextMixin, ListView):
    model = Question
    template_name = 'dashboard_worker/question/list.html'

    def get_queryset(self, **kwargs):
        questions = Question.objects.exclude(
            answered_questions__worker__pk=self.kwargs.get('worker_pk'))
        return questions

    def get_context_data(self, **kwargs):
        context = super(QuestionsListView, self).get_context_data()
        context['answered'] = Question.objects.filter(
            answered_questions__worker__pk=self.kwargs.get('worker_pk'))
        return context


@method_decorator((login_required, worker_access), name='dispatch')
class QuestionDetailView(QuestionContextMixin, DetailView):
    model = Question
    template_name = 'dashboard_worker/question/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(QuestionDetailView, self).get_context_data()
        question = get_object_or_404(Question, pk=self.kwargs.get('pk'))
        answer = Answer.objects.is_worker_answered(
            question=question, worker_pk=self.kwargs.get('worker_pk'))
        if answer:
            context['worker_answer'] = answer.answer

        return context


@method_decorator((login_required, worker_access), name='dispatch')
class AnswerAddSubmitForm(EduSkillJobAjaxMixin, CreateView):
    form_class = AnswerForm
    model = Answer

src/apps/answer/views.py
from django.views import generic

# from src.apps.answer.models import Answer
from src.apps.question.models import Answer


class AnswerListView(generic.ListView):
    model = Answer
    template_name = 'answer/list.html'

src/apps/resume/views.py
from django.views import generic

from .models import Resume


class ResumeDetailView(generic.DetailView):
    template_name = 'resume/detail_nouser.html'
    model = Resume

src/templates/vacancy/add_popup.html
{% load static %}
<html>
<head>
  <title>Add {{ field }}</title>
  <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
  <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
  <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
</head>
<body>
  <h1>Add {{ field }}</h1>
  <form method="POST" action="/add/{{ field }}/">
    <table>
      {{ form }}
    </table>
  <p><input type="submit" /> | <a href="javascript:window.close()">Cancel</a></p>
  </form>

</body>

</html>

src/templates/vacancy/create.html
{% extends 'base.html' %}
{% load i18n static %}
{% block head %}
  <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
  <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
  <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
{% endblock %}
{% block content %}
<main role="main" class="inner cover">
    <form method="post">
        {% csrf_token %}
        <fieldset>
          {% if operation == 'update' %}
            <legend>{% trans 'Fill up all fields' %}:</legend>
          {% else %}
            <legend>{% trans 'Create a new vacation' %}:</legend>
          {% endif %}
            <table class="table table-primary">
              {% for field in form %}
                <tr>
                {% if field.label != 'HRs' %}
                  <td>
                    {{ field.errors }}
                    {{ field.label_tag }}
                  </td>
                  <td>
                    {{ field }}
                    {% if field.help_text %}
                      <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                  </td>
                {% else %}
                  <div hidden>{{ field }}</div>
                {% endif %}
                </tr>
              {% endfor %}
            </table>
            {% if operation == 'update' %}
              <button type="submit" class="btn btn-primary">{% trans 'Update the vacation' %}</button>
            {% else %}
              <button type="submit" class="btn btn-primary">{% trans 'Create the vacation' %}</button>
            {% endif %}
        </fieldset>
    </form>
</main>
{% endblock %}

src/templates/vacancy/delete.html
{% extends 'base.html' %}
{% load i18n static %}

{% block content %}
  <main role="main" class="inner cover col-12">
    <br>
    <h4 class="mb-4">{% trans 'Do you realy want to delete the ' %}{{ object }}?</h4>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">{% trans 'Delete vacation' %}</button>
    </form>
  </main>
{% endblock %}

src/templates/vacancy/detail.html
{% load i18n %}

<main role="main" class="inner cover">
  <strong>{% trans 'Vacancy' %}:</strong><br>{{ object.title }}<br><br>
  <strong>{% trans 'Description' %}:</strong><br>{{ object.description }}<br><br>
  <strong>{% trans 'Tags' %}:</strong><br>{{ object.tags.all|join:", " }}<br><br>
  <br>
</main>

src/templates/vacancy/detail_nouser.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <main role="main" class="inner cover">
    <strong>{% trans 'Vacancy' %}:</strong><br>{{ object.title }}<br><br>
    <strong>{% trans 'Description' %}:</strong><br>{{ object.description }}<br><br>
    <strong>{% trans 'Tags' %}:</strong><br>{{ object.tags.all|join:", " }}<br><br>
        
    <br><br>
    <a href="javascript:history.back()">{% trans '&#8592; Go Back' %}</a>
  </main>
{% endblock %}

src/templates/vacancy/list.html
{% load i18n %}

<main role="main" class="inner cover col-12">
    <br>
    {% trans 'Vacancy list' %}:
    <br>
    <table class="table table-striped table-bordered">
        <th style="width: 30%;">{% trans 'Title' %}</th>
        <th>{% trans 'Description' %}</th>
        {% for vacancy in  object_list %}
            <tr>
                <td><a href="{% url 'vacancies:detail' vacancy.id %}">{{vacancy.title}}</a></td>
                <td>
                    {{vacancy.description|truncatechars:150}}
                    <a href="{% url 'vacancies:update' vacancy.id %}?next={{ request.path }}"> &#9998;</a>
                    <a href="{% url 'vacancies:delete' vacancy.id %}?next={{ request.path }}"> &#10008;</a>
                </td>
            </tr>
        {% endfor %}
    </table>

    <a href="javascript:history.back()">{% trans '&#8592; Go Back' %}</a>
</main>

src/templates/vacancy/vacancy_detail.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<main role="main" class="inner cover">
    {% trans 'Vacancy' %} {{ object.title }}:<br><br>
    {% trans 'Description' %}:<br>
    {{ object.description }}
</main>
{% endblock %}