src/apps/account_worker/urls.py
from django.urls import path
from .views import (
    AccountWorkerView,
    ResumeListView,
    ResumeUpdateView,
    ResumeCreateView,
    ResumeDeleteView,
    EducationUpdateView,
    EducationCreateView,
    EducationDeleteView,
    SkillCreateView,
    SkillUpdateView,
    SkillDeleteView,
    JobCreateView,
    JobUpdateView,
    JobDeleteView
)


app_name = 'dashboard_worker'

urlpatterns = [
    path('<pk>', AccountWorkerView.as_view(), name='dashboard_worker_main'),
    # Resume
    path('resume/<pk>', ResumeListView.as_view(), name='dashboard_worker_resume'),
    path('resume/create/<w_pk>', ResumeCreateView.as_view(), name='dashboard_worker_resume_create'),
    path('resume/update/<pk>/<w_pk>', ResumeUpdateView.as_view(),
         name='dashboard_worker_resume_update'),
    path('resume/delete/<pk>/<w_pk>', ResumeDeleteView.as_view(),
         name='dashboard_worker_resume_delete'),
    # Education
    path('education/update/<pk>/<res_pk>/<w_pk>', EducationUpdateView.as_view(),
         name='dashboard_worker_education_update'),
    path('education/create/<res_pk>/<w_pk>', EducationCreateView.as_view(),
         name='dashboard_worker_education_create'),
    path('education/delete/<pk>/<res_pk>/<w_pk>', EducationDeleteView.as_view(),
         name='dashboard_worker_education_delete'),
    # Skill
    path('skill/create/<res_pk>/<w_pk>', SkillCreateView.as_view(),
         name='dashboard_worker_skill_create'),
    path('skill/update/<pk>/<res_pk>/<w_pk>', SkillUpdateView.as_view(),
         name='dashboard_worker_skill_update'),
    path('skill/delete/<pk>/<res_pk>/<w_pk>', SkillDeleteView.as_view(),
         name='dashboard_worker_skill_delete'),
    # Job
    path('job/create/<res_pk>/<w_pk>', JobCreateView.as_view(),
         name='dashboard_worker_job_create'),
    path('job/update/<pk>/<res_pk>/<w_pk>', JobUpdateView.as_view(),
         name='dashboard_worker_job_update'),
    path('job/delete/<pk>/<res_pk>/<w_pk>', JobDeleteView.as_view(),
         name='dashboard_worker_job_delete'),
]

src/apps/answer/urls.py
from django.urls import path

from .views import AnswerListView

app_name = 'answer'

urlpatterns = [
    path('list/',
         AnswerListView.as_view(), name='list'),
]

src/apps/resume/urls.py
from django.urls import path

from .views import ResumeDetailView

app_name = 'resume'

urlpatterns = [
    path('detail/<int:pk>/',
         ResumeDetailView.as_view(), name='detail'),
]

src/apps/users/urls.py
from django.urls import path
from django.conf.urls import include

from src.apps.users.views import RegistrationView, ProfileView, LoginView


urlpatterns = [
    path('register/worker/', RegistrationView.as_view(),
         name='registration-user'),
    path('register/hr/', RegistrationView.as_view(),
         name='registration-hr'),
    path('register/profile/', ProfileView.as_view(),
         name='registration-profile'),
    path('login/', LoginView.as_view(),
         name='login'),
    # path('profile/update/<int:pk>/', ProfileView.as_view(), name='profile-update'),
    path('', include('django.contrib.auth.urls')),

]

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import TemplateView

from src.apps.users.views import RegistrationView, ProfileView, \
    ProfileUpdateView
from src.apps.vacancy.views import tag_create_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('role_choice/', TemplateView.as_view(
        template_name='registration/role_choice.html'), name='sign_up'),
    path('features/', TemplateView.as_view(
        template_name='components/features.html'), name='features'),
    path('contacts/', TemplateView.as_view(
        template_name='components/contacts.html'), name='contacts'),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('dashboard/worker/',
         include('src.apps.account_worker.urls'),
         name='dashboard_worker'),
    path('dashboard/hr/', include('src.apps.account_hr.urls',
         namespace='dashboard_hr')),
    path('accounts/', include('src.apps.users.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('vacancies/',
         include('src.apps.vacancy.urls', namespace='vacancies')),
    path('answers/',
         include('src.apps.answer.urls', namespace='answers')),
    path('resumes/',
         include('src.apps.resume.urls', namespace='resumes')),
    path('add/tags/', tag_create_view, name='tag_create'),
    path('terms/', TemplateView.as_view(
        template_name='components/terms_of_use.html'), name='terms'),
    path('privacy/', TemplateView.as_view(
        template_name='components/privacy_policy.html'), name='privacy'),
    path('questions/',
         include('src.apps.question.urls', namespace='questions')),
    path('profile_update/<int:pk>/', ProfileUpdateView.as_view(), name='profile_update')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/resume/models.py
from unidecode import unidecode

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.db.models.signals import pre_delete
from django.dispatch import receiver


class Education(models.Model):
    """ class education for resume(MTM) """

    period_edu = models.CharField(_('Period education'), max_length=50)
    name_institution = models.CharField(
        _('Name of institution'), max_length=100)
    faculty = models.CharField(_('Faculty'), max_length=100)
    form_study = models.CharField(_('Form of study'), max_length=30)

    class Meta:
        verbose_name = _('education')
        verbose_name_plural = _('educations')

    def __str__(self):
        return self.name_institution


class Skill(models.Model):
    """ class skill for resume(MTM) """

    name = models.CharField(_('Name'), max_length=30)

    class Meta:
        verbose_name = _('skill')
        verbose_name_plural = _('skills')

    def __str__(self):
        return self.name


class Job(models.Model):
    """ class job for resume(MTM) """

    period_work = models.CharField(_('Period of work'), max_length=50)
    position = models.CharField(_('Position'), max_length=100)
    name_company = models.CharField(_('Company name'), max_length=100)

    class Meta:
        verbose_name = _('job')
        verbose_name_plural = _('jobs')

    def __str__(self):
        return self.name_company


class Resume(models.Model):
    """ class resume for worker(MTM) """

    title = models.CharField(_('Title'), max_length=100, default='')
    other_skills = models.CharField(
        _('Other skills'), max_length=200, default='')
    hobbies = models.CharField(_('Hobbies'), max_length=200, default='')
    about = models.CharField(_('About'), max_length=400, default='')
    education = models.ManyToManyField(
        Education,
        related_name='educations',
        verbose_name=_('Education'),
    )
    skill = models.ManyToManyField(
        Skill,
        related_name='skills',
        verbose_name=_('Skills'),
    )
    job = models.ManyToManyField(
        Job,
        related_name='jobs',
        verbose_name=_('Jobs'),
    )
    slug = models.SlugField(_('Slug'), max_length=100, allow_unicode=True)
    created_at = models.DateTimeField(
        verbose_name=_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name=_('Updated_at'), auto_now=True)

    class Meta:
        verbose_name = _('resume')
        verbose_name_plural = _('resumes')

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        super(Resume, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    @property
    def educations(self):
        return ", ".join(
            [row.name_institution for row in self.education.all()]
        )

    @property
    def skills(self):
        return ", ".join([row.name for row in self.skill.all()])

    @property
    def jobs(self):
        return ", ".join([row.name_company for row in self.job.all()])


@receiver(pre_delete, sender=Resume)
def pre_delete_story(sender, instance, **kwargs):
    for edu in instance.education.all():
        edu.delete()
    for skill in instance.skill.all():
        skill.delete()
    for job in instance.job.all():
        job.delete()

src/apps/account_hr/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from src.apps.question.models import Answer, Question
from src.apps.resume.models import Resume
from src.apps.vacancy.models import Vacancy
from .models import AccountHr


class DashboardView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/index.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['vacancies'] = Vacancy.objects.filter(
            account_hr__user_id=self.request.user.id
        )[:5]
        context['answers'] = Answer.objects.filter(
            question__account_hr__user_id=self.request.user.id
        )[:5]
        return context


class DashboardVacancyListView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/vacancy/list.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardVacancyListView, self).get_context_data(**kwargs)
        context['vacancies'] = Vacancy.objects.filter(
            account_hr__user_id=self.request.user.id
        )
        return context


class DashboardAnswerListView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/answer/list.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardAnswerListView, self).get_context_data(**kwargs)
        context['object_list'] = Answer.objects.filter(
            question__account_hr__user_id=self.request.user.id
        )
        return context


class DashboardResumeListView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/resume/list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardResumeListView, self).get_context_data(**kwargs)
        context['object_list'] = Resume.objects.all()
        return context


class DashboardResumeDetailView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/resume/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardResumeDetailView, self).get_context_data(**kwargs)
        context['object'] = Resume.objects.get(id=kwargs['pk'])
        return context


class DashboardVacancyDetailView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/vacancy/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardVacancyDetailView, self).get_context_data(**kwargs)
        vacancy = Vacancy.objects.get(id=kwargs['pk'])
        context['object'] = vacancy
        context['questions'] = Question.objects.filter(vacancy=vacancy)
        return context

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        return reverse_lazy('dashboard_hr:main')

src/apps/account_worker/views/education.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from src.apps.resume.models import Education
from ..forms import EducationForm
from .mixins import (
    EduSkillJobSuccessUrlMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobAjaxMixin, worker_access)


@method_decorator((login_required, worker_access), name='dispatch')
class EducationUpdateView(ResumeEduSkillJobContextMixin,
                          EduSkillJobSuccessUrlMixin, UpdateView):
    form_class = EducationForm
    model = Education
    template_name = 'dashboard_worker/education/update.html'


@method_decorator((login_required, worker_access), name='dispatch')
class EducationCreateView(
    EduSkillJobSuccessUrlMixin, EduSkillJobAjaxMixin,
    ResumeEduSkillJobContextMixin, CreateView
):
    form_class = EducationForm
    model = Education
    template_name = 'dashboard_worker/education/create.html'


@method_decorator((login_required, worker_access), name='dispatch')
class EducationDeleteView(ResumeEduSkillJobContextMixin,
                          EduSkillJobSuccessUrlMixin, DeleteView):
    model = Education
    template_name = 'dashboard_worker/education/delete.html'

src/apps/account_worker/views/job.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from src.apps.resume.models import Job
from ..forms import JobForm
from .mixins import (
    EduSkillJobSuccessUrlMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobAjaxMixin, worker_access)


@method_decorator((login_required, worker_access), name='dispatch')
class JobCreateView(
    EduSkillJobAjaxMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobSuccessUrlMixin, CreateView
):
    form_class = JobForm
    model = Job
    template_name = 'dashboard_worker/job/create.html'


@method_decorator((login_required, worker_access), name='dispatch')
class JobUpdateView(ResumeEduSkillJobContextMixin,
                    EduSkillJobSuccessUrlMixin, UpdateView):
    form_class = JobForm
    model = Job
    template_name = 'dashboard_worker/job/update.html'


@method_decorator((login_required, worker_access), name='dispatch')
class JobDeleteView(ResumeEduSkillJobContextMixin,
                    EduSkillJobSuccessUrlMixin, DeleteView):
    model = Job
    template_name = 'dashboard_worker/job/delete.html'

src/apps/account_worker/views/question.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

from src.apps.question.models import Question, Answer
from ..forms import AnswerForm
from .mixins import (
    worker_access, QuestionContextMixin, EduSkillJobAjaxMixin)


@method_decorator((login_required, worker_access), name='dispatch')
class QuestionsListView(QuestionContextMixin, ListView):
    model = Question
    template_name = 'dashboard_worker/question/list.html'

    def get_queryset(self, **kwargs):
        questions = Question.objects.exclude(
            answered_questions__worker__pk=self.kwargs.get('worker_pk'))
        return questions

    def get_context_data(self, **kwargs):
        context = super(QuestionsListView, self).get_context_data()
        context['answered'] = Question.objects.filter(
            answered_questions__worker__pk=self.kwargs.get('worker_pk'))
        return context


@method_decorator((login_required, worker_access), name='dispatch')
class QuestionDetailView(QuestionContextMixin, DetailView):
    model = Question
    template_name = 'dashboard_worker/question/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(QuestionDetailView, self).get_context_data()
        question = get_object_or_404(Question, pk=self.kwargs.get('pk'))
        answer = Answer.objects.is_worker_answered(
            question=question, worker_pk=self.kwargs.get('worker_pk'))
        if answer:
            context['worker_answer'] = answer.answer

        return context


@method_decorator((login_required, worker_access), name='dispatch')
class AnswerAddSubmitForm(EduSkillJobAjaxMixin, CreateView):
    form_class = AnswerForm
    model = Answer

src/apps/account_worker/views/skill.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from src.apps.resume.models import Skill
from ..forms import SkillForm
from .mixins import (
    EduSkillJobSuccessUrlMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobAjaxMixin, worker_access)


@method_decorator((login_required, worker_access), name='dispatch')
class SkillUpdateView(ResumeEduSkillJobContextMixin,
                      EduSkillJobSuccessUrlMixin, UpdateView):
    form_class = SkillForm
    model = Skill
    template_name = 'dashboard_worker/skill/update.html'


@method_decorator((login_required, worker_access), name='dispatch')
class SkillDeleteView(ResumeEduSkillJobContextMixin,
                      EduSkillJobSuccessUrlMixin, DeleteView):
    model = Skill
    template_name = 'dashboard_worker/skill/delete.html'


@method_decorator((login_required, worker_access), name='dispatch')
class SkillCreateView(
    EduSkillJobAjaxMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobSuccessUrlMixin, CreateView
):
    form_class = SkillForm
    model = Skill
    template_name = 'dashboard_worker/skill/create.html'

src/apps/answer/views.py
from django.views import generic

# from src.apps.answer.models import Answer
from src.apps.question.models import Answer


class AnswerListView(generic.ListView):
    model = Answer
    template_name = 'answer/list.html'

src/templates/dashboard_worker/education/create.html
{% extends 'base.html' %}
{% load i18n %}
{% block head %}
{% endblock %}
{% block content %}
  <div class="border-0 mt-3" style="">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item"> <a href="{% url 'dashboard_worker:dashboard_worker_resume' pk=worker_pk %}" class="nav-link">{% trans 'My resume' %}</a> </li>
            <li class="nav-item"> <a class="nav-link active" href="{% url 'dashboard_worker:dashboard_worker_resume_update' pk=resume_pk worker_pk=worker_pk %}">{{ title }}</a> </li>
          </ul>
        </div>
      </div>
      <div class="row justify-content-center text-left">
        <div class="col-md-12">
          <div class="row">
            <div class="mx-auto p-4 col-lg-10">
              <h1 class="mb-4">{% trans 'Create education:' %}</h1>
              <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                  <label for="id_period_edu">{% trans 'Period education:' %}</label>
                  {{ form.period_edu }}
                  {{ form.period_edu.errors }}
                </div>
                <div class="form-group">
                  <label for="id_name_institution">{% trans 'Name of institution:' %}</label>
                  {{ form.name_institution }}
                  {{ form.name_institution.errors }}
                </div>
                <div class="form-group">
                  <label for="id_faculty">{% trans 'Faculty:' %}</label>
                  {{ form.faculty }}
                  {{ form.faculty.errors }}
                </div>
                <div class="form-group">
                  <label for="id_form_study">{% trans 'Form of study:' %}</label>
                  {{ form.form_study }}
                  {{ form.form_study.errors }}
                </div>
                <hr>
                <button type="submit" class="btn btn-primary">{% trans 'Create education' %}</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/dashboard_worker/education/delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block head %}
{% endblock %}
{% block content %}
  <div class="border-0 mt-3" style="">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item"> <a href="{% url 'dashboard_worker:dashboard_worker_resume' pk=worker_pk %}" class="nav-link">{% trans 'My resume' %}</a> </li>
            <li class="nav-item"> <a class="nav-link active" href="{% url 'dashboard_worker:dashboard_worker_resume_update' pk=resume_pk worker_pk=worker_pk %}">{{ title }}</a> </li>
          </ul>
        </div>
      </div>
      <div class="row justify-content-center text-left">
        <div class="col-md-12">
          <div class="row">
            <div class="mx-auto p-4 col-lg-10">
              <h1 class="mb-4">{% trans 'Delete education:' %}</h1>
              <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <hr>
                <button type="submit" class="btn btn-primary">{% trans 'Delete education' %}</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/dashboard_worker/education/update.html
{% extends 'base.html' %}
{% load i18n %}
{% block head %}
{% endblock %}
{% block content %}
  <div class="border-0 mt-3" style="">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item"> <a href="{% url 'dashboard_worker:dashboard_worker_resume' pk=worker_pk %}" class="nav-link">{% trans 'My resume' %}</a> </li>
            <li class="nav-item"> <a class="nav-link active" href="{% url 'dashboard_worker:dashboard_worker_resume_update' pk=resume_pk worker_pk=worker_pk %}">{{ title }}</a> </li>
          </ul>
        </div>
      </div>
      <div class="row justify-content-center text-left">
        <div class="col-md-12">
          <div class="row">
            <div class="mx-auto p-4 col-lg-10">
              <h1 class="mb-4">{{ title }} - {% trans 'Education:' %}</h1>
              <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                  <label for="id_period_edu">{% trans 'Period education:' %}</label>
                  {{ form.period_edu }}
                  {{ form.period_edu.errors }}
                </div>
                <div class="form-group">
                  <label for="id_name_institution">{% trans 'Name of institution:' %}</label>
                  {{ form.name_institution }}
                  {{ form.name_institution.errors }}
                </div>
                <div class="form-group">
                  <label for="id_faculty">{% trans 'Faculty:' %}</label>
                  {{ form.faculty }}
                  {{ form.faculty.errors }}
                </div>
                <div class="form-group">
                  <label for="id_form_study">{% trans 'Form of study:' %}</label>
                  {{ form.form_study }}
                  {{ form.form_study.errors }}
                </div>
                <hr>
                <button type="submit" class="btn btn-primary">{% trans 'Update education' %}</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}