src/apps/account_hr/urls.py
from django.urls import path

from .views import DashboardView, DashboardVacancyListView, \
    DashboardAnswerListView, DashboardResumeListView, \
    DashboardResumeDetailView, DashboardVacancyDetailView

app_name = 'account_hr'

urlpatterns = [
    path('', DashboardView.as_view(), name='main'),
    path('vacancies/', DashboardVacancyListView.as_view(), name='vacancies'),
    path(
        'vacancies/<int:pk>/',
        DashboardVacancyDetailView.as_view(),
        name='vacancy_detail'
    ),
    path('answers/', DashboardAnswerListView.as_view(), name='answers'),
    path('resumes/', DashboardResumeListView.as_view(), name='resumes'),
    path(
        'resumes/<int:pk>', DashboardResumeDetailView.as_view(), name='resume'
    ),
]

src/apps/account_worker/urls.py
from django.urls import path
from .views import (
    AccountWorkerView,
    ResumeListView,
    ResumeUpdateView,
    ResumeCreateView,
    ResumeDeleteView,
    EducationUpdateView,
    EducationCreateView,
    EducationDeleteView,
    SkillCreateView,
    SkillUpdateView,
    SkillDeleteView,
    JobCreateView,
    JobUpdateView,
    JobDeleteView
)


app_name = 'dashboard_worker'

urlpatterns = [
    path('<pk>', AccountWorkerView.as_view(), name='dashboard_worker_main'),
    # Resume
    path('resume/<pk>', ResumeListView.as_view(), name='dashboard_worker_resume'),
    path('resume/create/<w_pk>', ResumeCreateView.as_view(), name='dashboard_worker_resume_create'),
    path('resume/update/<pk>/<w_pk>', ResumeUpdateView.as_view(),
         name='dashboard_worker_resume_update'),
    path('resume/delete/<pk>/<w_pk>', ResumeDeleteView.as_view(),
         name='dashboard_worker_resume_delete'),
    # Education
    path('education/update/<pk>/<res_pk>/<w_pk>', EducationUpdateView.as_view(),
         name='dashboard_worker_education_update'),
    path('education/create/<res_pk>/<w_pk>', EducationCreateView.as_view(),
         name='dashboard_worker_education_create'),
    path('education/delete/<pk>/<res_pk>/<w_pk>', EducationDeleteView.as_view(),
         name='dashboard_worker_education_delete'),
    # Skill
    path('skill/create/<res_pk>/<w_pk>', SkillCreateView.as_view(),
         name='dashboard_worker_skill_create'),
    path('skill/update/<pk>/<res_pk>/<w_pk>', SkillUpdateView.as_view(),
         name='dashboard_worker_skill_update'),
    path('skill/delete/<pk>/<res_pk>/<w_pk>', SkillDeleteView.as_view(),
         name='dashboard_worker_skill_delete'),
    # Job
    path('job/create/<res_pk>/<w_pk>', JobCreateView.as_view(),
         name='dashboard_worker_job_create'),
    path('job/update/<pk>/<res_pk>/<w_pk>', JobUpdateView.as_view(),
         name='dashboard_worker_job_update'),
    path('job/delete/<pk>/<res_pk>/<w_pk>', JobDeleteView.as_view(),
         name='dashboard_worker_job_delete'),
]

src/apps/answer/urls.py
from django.urls import path

from .views import AnswerListView

app_name = 'answer'

urlpatterns = [
    path('list/',
         AnswerListView.as_view(), name='list'),
]

src/apps/resume/urls.py
from django.urls import path

from .views import ResumeDetailView

app_name = 'resume'

urlpatterns = [
    path('detail/<int:pk>/',
         ResumeDetailView.as_view(), name='detail'),
]

src/apps/users/urls.py
from django.urls import path
from django.conf.urls import include

from src.apps.users.views import RegistrationView, ProfileView, LoginView


urlpatterns = [
    path('register/worker/', RegistrationView.as_view(),
         name='registration-user'),
    path('register/hr/', RegistrationView.as_view(),
         name='registration-hr'),
    path('register/profile/', ProfileView.as_view(),
         name='registration-profile'),
    path('login/', LoginView.as_view(),
         name='login'),
    # path('profile/update/<int:pk>/', ProfileView.as_view(), name='profile-update'),
    path('', include('django.contrib.auth.urls')),

]

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import TemplateView

from src.apps.users.views import RegistrationView, ProfileView, \
    ProfileUpdateView
from src.apps.vacancy.views import tag_create_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('role_choice/', TemplateView.as_view(
        template_name='registration/role_choice.html'), name='sign_up'),
    path('features/', TemplateView.as_view(
        template_name='components/features.html'), name='features'),
    path('contacts/', TemplateView.as_view(
        template_name='components/contacts.html'), name='contacts'),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('dashboard/worker/',
         include('src.apps.account_worker.urls'),
         name='dashboard_worker'),
    path('dashboard/hr/', include('src.apps.account_hr.urls',
         namespace='dashboard_hr')),
    path('accounts/', include('src.apps.users.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('vacancies/',
         include('src.apps.vacancy.urls', namespace='vacancies')),
    path('answers/',
         include('src.apps.answer.urls', namespace='answers')),
    path('resumes/',
         include('src.apps.resume.urls', namespace='resumes')),
    path('add/tags/', tag_create_view, name='tag_create'),
    path('terms/', TemplateView.as_view(
        template_name='components/terms_of_use.html'), name='terms'),
    path('privacy/', TemplateView.as_view(
        template_name='components/privacy_policy.html'), name='privacy'),
    path('questions/',
         include('src.apps.question.urls', namespace='questions')),
    path('profile_update/<int:pk>/', ProfileUpdateView.as_view(), name='profile_update')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/account_hr/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from src.apps.question.models import Answer, Question
from src.apps.resume.models import Resume
from src.apps.vacancy.models import Vacancy
from .models import AccountHr


class DashboardView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/index.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['vacancies'] = Vacancy.objects.filter(
            account_hr__user_id=self.request.user.id
        )[:5]
        context['answers'] = Answer.objects.filter(
            question__account_hr__user_id=self.request.user.id
        )[:5]
        return context


class DashboardVacancyListView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/vacancy/list.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardVacancyListView, self).get_context_data(**kwargs)
        context['vacancies'] = Vacancy.objects.filter(
            account_hr__user_id=self.request.user.id
        )
        return context


class DashboardAnswerListView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/answer/list.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardAnswerListView, self).get_context_data(**kwargs)
        context['object_list'] = Answer.objects.filter(
            question__account_hr__user_id=self.request.user.id
        )
        return context


class DashboardResumeListView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/resume/list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardResumeListView, self).get_context_data(**kwargs)
        context['object_list'] = Resume.objects.all()
        return context


class DashboardResumeDetailView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/resume/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardResumeDetailView, self).get_context_data(**kwargs)
        context['object'] = Resume.objects.get(id=kwargs['pk'])
        return context


class DashboardVacancyDetailView(LoginRequiredMixin, TemplateView):
    model = AccountHr
    template_name = 'dashboard_hr/vacancy/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardVacancyDetailView, self).get_context_data(**kwargs)
        vacancy = Vacancy.objects.get(id=kwargs['pk'])
        context['object'] = vacancy
        context['questions'] = Question.objects.filter(vacancy=vacancy)
        return context

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        return reverse_lazy('dashboard_hr:main')

src/apps/account_worker/views/education.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from src.apps.resume.models import Education
from ..forms import EducationForm
from .mixins import (
    EduSkillJobSuccessUrlMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobAjaxMixin, worker_access)


@method_decorator((login_required, worker_access), name='dispatch')
class EducationUpdateView(ResumeEduSkillJobContextMixin,
                          EduSkillJobSuccessUrlMixin, UpdateView):
    form_class = EducationForm
    model = Education
    template_name = 'dashboard_worker/education/update.html'


@method_decorator((login_required, worker_access), name='dispatch')
class EducationCreateView(
    EduSkillJobSuccessUrlMixin, EduSkillJobAjaxMixin,
    ResumeEduSkillJobContextMixin, CreateView
):
    form_class = EducationForm
    model = Education
    template_name = 'dashboard_worker/education/create.html'


@method_decorator((login_required, worker_access), name='dispatch')
class EducationDeleteView(ResumeEduSkillJobContextMixin,
                          EduSkillJobSuccessUrlMixin, DeleteView):
    model = Education
    template_name = 'dashboard_worker/education/delete.html'

src/apps/account_worker/views/job.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from src.apps.resume.models import Job
from ..forms import JobForm
from .mixins import (
    EduSkillJobSuccessUrlMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobAjaxMixin, worker_access)


@method_decorator((login_required, worker_access), name='dispatch')
class JobCreateView(
    EduSkillJobAjaxMixin, ResumeEduSkillJobContextMixin,
    EduSkillJobSuccessUrlMixin, CreateView
):
    form_class = JobForm
    model = Job
    template_name = 'dashboard_worker/job/create.html'


@method_decorator((login_required, worker_access), name='dispatch')
class JobUpdateView(ResumeEduSkillJobContextMixin,
                    EduSkillJobSuccessUrlMixin, UpdateView):
    form_class = JobForm
    model = Job
    template_name = 'dashboard_worker/job/update.html'


@method_decorator((login_required, worker_access), name='dispatch')
class JobDeleteView(ResumeEduSkillJobContextMixin,
                    EduSkillJobSuccessUrlMixin, DeleteView):
    model = Job
    template_name = 'dashboard_worker/job/delete.html'

src/apps/account_worker/views/mixins.py
from django.urls import reverse_lazy
from django.views.generic.base import ContextMixin
from django.shortcuts import get_object_or_404
from django.http import JsonResponse, Http404
from django.contrib.auth import get_user_model

from src.apps.resume.models import Resume
from src.apps.question.models import Question
from ..models import WorkerAnswered


User = get_user_model()


class EduSkillJobSuccessUrlMixin:
    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'dashboard_worker:dashboard_worker_resume_update',
            kwargs={
                'pk': self.kwargs.get('resume_pk'),
                'worker_pk': self.kwargs.get('worker_pk')
            }
        )


class ResumeEduSkillJobContextMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        context = super(
            ResumeEduSkillJobContextMixin, self).get_context_data(**kwargs)
        if self.kwargs.get('resume_pk'):
            context['resume_pk'] = self.kwargs.get('resume_pk')
            resume = get_object_or_404(Resume, pk=self.kwargs.get('resume_pk'))
        else:
            context['resume_pk'] = self.kwargs.get('pk')
            resume = get_object_or_404(Resume, pk=self.kwargs.get('pk'))
        context['title'] = resume.title
        context['worker_pk'] = self.kwargs.get('worker_pk')
        return context


class EduSkillJobAjaxMixin:
    def form_invalid(self, form):
        if self.request.is_ajax():
            if self.request.POST['tag'] == 'create':
                form = self.form_class()
                response_dict = {'response': str(form)}
                return JsonResponse(response_dict)
            raise Http404
        else:
            return super(EduSkillJobAjaxMixin, self).form_invalid(form)

    def form_valid(self, form):
        if self.request.is_ajax():
            if self.request.POST['tag'] == 'add':
                form = self.form_class(self.request.POST)
                if form.is_valid():
                    if self.form_class.__name__ == 'AnswerForm':
                        form.save(commit=False)
                        form.instance.question = get_object_or_404(Question, pk=self.request.POST['question'])
                        form.save()
                        user = get_object_or_404(User, pk=self.request.user.pk)
                        worker = user.workers.is_created(user=user)
                        if user.workers.is_created(user=user).answer.filter(
                                question=form.instance.question.pk).first():
                            answer = user.workers.is_created(user=user).answer.get(
                                question=form.instance.question.pk)
                            user.workers.is_created(user=user).answer.remove(answer)
                            answer.delete()
                        user.workers.is_created(user=user).answer.add(form.instance)
                        form.save()
                        answered = WorkerAnswered.objects.create(
                            worker=worker, question=form.instance.question,
                            answer=form.instance)
                        answered.save()
                        response_dict = {'response': form.instance.answer}
                    form.save()
                    if self.form_class.__name__ == 'EducationForm':
                        response_dict = {
                            'id': form.instance.pk,
                            'name_institution': form.instance.name_institution
                        }
                    elif self.form_class.__name__ == 'SkillForm':
                        response_dict = {
                            'id': form.instance.pk,
                            'name': form.instance.name
                        }
                    elif self.form_class.__name__ == 'JobForm':
                        response_dict = {
                            'id': form.instance.pk,
                            'name_company': form.instance.name_company
                        }
                    return JsonResponse(response_dict)
            else:
                raise Http404
        obj = form.save(commit=False)
        resume = get_object_or_404(Resume, pk=self.kwargs.get('resume_pk'))
        obj.save()
        if self.form_class.__name__ == 'EducationForm':
            resume.education.add(obj)
        elif self.form_class.__name__ == 'SkillForm':
            resume.skill.add(obj)
        elif self.form_class.__name__ == 'JobForm':
            resume.job.add(obj)
        resume.save()
        return super(EduSkillJobAjaxMixin, self).form_valid(form)


def worker_access(function):
    def wrapper(request, *args, **kwargs):
        if request.is_ajax():
            return function(request, *args, **kwargs)

        user = get_object_or_404(User, username=request.user)
        worker = user.workers.is_created(user=user)
        pk = kwargs.get('worker_pk') or kwargs.get('pk')
        if worker.pk != int(pk):
            raise Http404

        return function(request, *args, **kwargs)

    return wrapper


class QuestionContextMixin(ContextMixin):
    def get_context_data(self, *args, **kwargs):
        context = super(
            QuestionContextMixin, self).get_context_data(**kwargs)
        context['worker_pk'] = self.kwargs.get('worker_pk')
        return context

src/apps/answer/views.py
from django.views import generic

# from src.apps.answer.models import Answer
from src.apps.question.models import Answer


class AnswerListView(generic.ListView):
    model = Answer
    template_name = 'answer/list.html'

src/apps/resume/views.py
from django.views import generic

from .models import Resume


class ResumeDetailView(generic.DetailView):
    template_name = 'resume/detail_nouser.html'
    model = Resume

src/templates/components/contacts.html
{% extends 'base.html' %}
{% load i18n static staticfiles %}

{% block content %}
    <div class="row text-center mt-3">
        <div class="col">
            <h1 class="cover-heading">{% trans 'Contacts' %}</h1>
            <br><br>
            <p class="lead">{% trans 'Please, do not hesitate to ask us any question you have via email ' %} support@video-resume.com.<br><br></p>
        </div>
    </div>
{% endblock %}

src/templates/components/contacts_old.html
{% extends 'base.html' %}
{% load i18n static staticfiles %}

{% block content %}
    <main role="main" class="inner cover">
        <h1 class="cover-heading">{% trans 'Contacts' %}</h1>
        <br><br>
        <p class="lead">{% trans 'Please, do not hesitate to ask us any question you have via email ' %} support@video-resume.com.<br><br></p>
    </main>
{% endblock %}

src/templates/components/features.html
{% extends 'base.html' %}
{% load i18n static staticfiles %}

{% block content %}
    <div class="row text-center mt-3">
        <div class="col">
            <h1 class="cover-heading">{% trans 'Video resume is a new way to your success!' %}</h1>
            <p class="lead">{% trans 'The Reasons are as follows:' %}<br><br>
                    {% trans 'First reason: more simplicity to create a summary' %} <br><br>
                    {% trans 'Second reason: video resume contains more information about your personality than a written one' %} <br><br>
                    {% trans 'Third reason: more chanсes to give a relevant response' %} <br><br>
            </p>
            <p class="lead">
              <a href="#" class="btn btn-lg btn-secondary">{% trans 'Start recording a new perfect resume' %}</a>
            </p>
        </div>
    </div>
{% endblock %}

src/templates/components/features_old.html
{% extends 'base.html' %}
{% load i18n static staticfiles %}

{% block content %}
    <main role="main" class="inner cover">
        <h1 class="cover-heading">{% trans 'Video resume is a new way to your success!' %}</h1>
        <p class="lead">{% trans 'The Reasons are as follows:' %}<br><br>
                {% trans 'First reason: more simplicity to create a summary' %} <br><br>
                {% trans 'Second reason: video resume contains more information about your personality than a written one' %} <br><br>
                {% trans 'Third reason: more chanсes to give a relevant response' %} <br><br>
        </p>
        <p class="lead">
          <a href="#" class="btn btn-lg btn-secondary">{% trans 'Start recording a new perfect resume' %}</a>
        </p>
    </main>
{% endblock %}

src/templates/components/footer1.html
{% load i18n static staticfiles %}

<footer class="navbar fixed-bottom page-footer font-small navbar-dark bg-dark text-white">
    <div class="footer-copyright text-center py-3">{% now "Y" %}. {% trans 'All rights reserved. Designed by ' %}
        <a href="#"> Sargus Software</a>
    </div>

</footer>

src/templates/components/footer1_old.html
{% load i18n static staticfiles %}

<footer class="mastfoot mt-auto">
    <div class="nav-link">
      <p>{% now "Y" %}. {% trans 'All rights reserved. Designed by ' %}<a href="#">Sargus Software</a></p>
    </div>
</footer>

src/templates/components/last_questions.html
{% if questions %}
  <strong>Last questions:</strong>
  <br>
  <div class="my-slider">
    {% for question in questions %}
        <div>
<!--          <a href="{% url 'questions:detail' question.id %}">-->
            <h4>{{ question.title }}</h4>
            {{ question.text }}
<!--          </a>-->
        </div>
    {% endfor %}
  </div>
{% endif %}

src/templates/components/last_resumes.html
{% load i18n static staticfiles %}

{% if resumes %}
  <hr>
  <strong>{% trans 'Last resumes:' %}</strong>
  <br>
  <div class="resume-slider">
    {% for resume in resumes %}
        <div>
          <a href="{% url 'resumes:detail' resume.id %}">
            <h4>{{ resume.title }}</h4>
            {{ resume.about }}
          </a>
        </div>
    {% endfor %}
  </div>
{% endif %}

src/templates/components/last_vacancies.html
{% load i18n static staticfiles %}

{% if vacancies %}
  <hr></hr>
  <strong>{% trans 'Last vacancies:' %}</strong>
  <br>
  <div class="vacancy-slider">
    {% for vacancy in vacancies %}
        <div>
          <a href="{% url 'vacancies:detail' vacancy.id %}">
            <h4>{{ vacancy.title }}</h4>
            {{vacancy.description}}
          </a>
        </div>
    {% endfor %}
  </div>
{% endif %}

src/templates/components/navbar.html
{% load i18n static staticfiles %}
{% load dashboard_tag %}
{% dashboard_tag as dashboard %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Video-resume</a>
  <div class="navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <a class="nav-link main_page" href="{% url 'index' %}">{% trans 'Home' %}<span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
            <a class="nav-link features" href="{% url 'features' %}">{% trans 'Features' %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link contacts" href="{% url 'contacts' %}">{% trans 'Contacts' %}</a>
        </li>
        {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" title="User profile" href="{% url 'profile_update' request.user.profile.id %}">{% trans 'Profile' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link role_choice" href="{% url 'sign_up' %}">{% trans 'Sign up' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link login" href="{% url 'login' %}">{% trans 'Login' %}</a>
            </li>
        {% endif %}
        {% if worker_pk %}
            <li class="nav-item">
                <a class="nav-link dashboard" href="{% url 'dashboard_worker:dashboard_worker_main' pk=worker_pk %}">{% trans 'Dashboard' %}</a>
            </li>
        {% endif %}
        {% if hr %}
            <li class="nav-item">
                <a class="nav-link dashboard" href="{% url 'dashboard_hr:main' %}">{% trans 'Dashboard' %}</a>
            </li>
        {% endif %}
        <li class="nav-item">
            <div class="mt-1" style="width: 200px;">
                  <form action="{% url 'set_language' %}" method="post" class="send-lang">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}">
                        <select name="language" id="select-lang">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                    {{ language.name_local }} ({{ language.code }})
                                </option>
                            {% endfor %}
                        </select>
                  </form>
            </div>
        </li>
    </ul>
  </div>
</nav>

src/templates/components/navbar_old.html
{% load i18n static staticfiles %}
{% load dashboard_tag %}
{% dashboard_tag as dashboard %}

<header class="masthead mb-4">
  <div class="inner">
      <div class="row">
        <h3 class="masthead-brand" >{% trans 'Video Resume' %}</h3>
        <nav class="justify-content-center ml-3">
          <div class="nav nav-masthead login-block">
            {% if request.user.is_authenticated %}
              <a class="nav-link" title="User profile" href="#">{% trans 'Profile' %}</a>
              <a class="nav-link" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
            {% else %}
              <a class="nav-link role_choice" href="{% url 'sign_up' %}">{% trans 'Sign up' %}</a>
              <a class="nav-link login" href="{% url 'login' %}">{% trans 'Login' %}</a>
            {% endif %}
          </div>
          <div class="nav nav-masthead ">
            <a class="nav-link main_page" href="{% url 'index' %}">{% trans 'Main' %}</a>
            {% if worker_pk %}
              <a class="nav-link dashboard" href="{% url 'dashboard_worker:dashboard_worker_main' pk=worker_pk %}">{% trans 'Dashboard' %}</a>
            {% endif %}
            <a class="nav-link features" href="{% url 'features' %}">{% trans 'Features' %}</a>
            <a class="nav-link contacts" href="{% url 'contacts' %}">{% trans 'Contacts' %}</a>
          </div>
        </nav>
      </div>
      <div class="row">
          <div class="" style="width: 200px;">
              <form action="{% url 'set_language' %}" method="post" class="send-lang">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select name="language" id="select-lang">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                </form>
          </div>
      </div>
  </div>
</header>